### ISSUE TITLE
[Fix] 아기사자 출석 정보 확인 페이지 디테일 수정

### ISSUE THREAD

**Issue by nakyeongg** [likelion-community/likelion-community-frontend#41]
## ✔️ Issue

아기사자 출석 정보 확인 페이지 수정합니다

## 📝 To-do

- [x] 전체 padding 수정
- [x] 버튼 하단에 고정
- [x] 세션 내용 폰트 색상 변경
- [x] 출석 현황 배경 사이즈 1:1로 수정

## 🛠 Working time

1D
