### ISSUE TITLE
[Feature] 게시판 목록 페이지 구현

### ISSUE THREAD

**Issue by nakyeongg** [likelion-community/likelion-community-frontend#44]
## ✔️ Issue

게시판 목록 페이지를 구현합니다

## 📝 To-do
- 전체 커뮤니티
- [x] 커뮤니티 메인 페이지 UI
- [x] 트랙별 게시판 목록 페이지 UI
- [x] 아기사자 게시판 목록 페이지 UI
- [x] 이벤트/공지 게시판 목록 페이지 UI
- [x] 참여 게시판 목록 페이지 UI

- 학교 커뮤니티
- [x] 전체 게시판 목록 페이지 UI
- [x] 질문 게시판 목록 페이지 UI

## 🛠 Working time

1D
