### ISSUE TITLE
[Fix] 메인 홈 컴포넌트 사이즈 수정

### ISSUE THREAD

**Issue by nakyeongg** [likelion-community/likelion-community-frontend#75]
## ✔️ Issue

메인 홈의 컴포넌트 사이즈를 수정합니다

## 📝 To-do

- [x] 슬라이드 3개로 변경
- [x] content div 가로 길이 변경
- [x] main header의 세로 길이 변경
- [x] 전체 게시판의 종류가 나오도록 수정
