### ISSUE TITLE
[Feature] 메인 커뮤니티 API 연결

### ISSUE THREAD

**Issue by nakyeongg** [likelion-community/likelion-community-frontend#80]
## ✔️ Issue

메인 커뮤니티의 API를 연결합니다

## 📝 To-do

- [x] 홈 화면
- [x] 게시판별 목록 페이지
- [x] 게시글 상세 페이지 작성
- [x] 게시글 상세 페이지 수정
- [x] 게시글 상세 페이지 삭제
- [x] 게시글 댓글

## 🛠 Working time

1D
