### ISSUE TITLE
[Feature] 운영진&아기사자 출석부분 API연결,필요한 수정사항들 수정

### ISSUE THREAD

**Issue by nicerjs23** [likelion-community/likelion-community-frontend#86]
## ✔️ Issue

운영진 출석, 출석등록, 출석관리 API연결합니다.. ++아기사자 출석부분도 다 엮여있어서 같이합니다 

## 📝 To-do

- [x] 운영진 출석 리스트 연결
- [x] 운영진 출석 등록 연결
- [x] 운영진 출석관리 연결
- [x] 학교메인에서 아기사자,운영진 구분해서 출석페이지 넘기기 
- [x] 아기사자 출석페이지 
- [x] 아기사자 출석 상세페이지 
- [x] 아기사자 인증코드 입력페이지 

## 🛠 Working time

해커톤전까지.,,
