### ISSUE TITLE
[Fix] 아기사자 출석부분 수정

### ISSUE THREAD

**Issue by nicerjs23** [likelion-community/likelion-community-frontend#88]
## ✔️ Issue

변경된디자인에 맞게 아기사자 출석 부분을 수정하고 하드코딩된부분도 api연결에 맞게 수정하겠습니다. 

## 📝 To-do

- [x] 아기사자 출석 상세페이지 수정
- [x] 아기사자 출석 리스트 새로만들기 
- [x] 아기사자 출석 인증코드 입력 수정 

## 🛠 Working time

1D
